### ISSUE TITLE
The order in which the next action predicate consults the state predicates is undetermined

### ISSUE THREAD

**Issue by sompylasar** [509dave16/tic-tac-toe-engine#7]
The order is determimed by the for..in loop which is unpredictable.

https://github.com/509dave16/tic-tac-toe-engine/blob/4f398bd95a0f283de4c646a08baab7bad2b4e2c6/src/sam/nap.js#L31

```
  return present => {
    for (const controlState in controlStateToActions) {
      if(state[controlState](model)) {
        const action = controlStateToActions[controlState];
        action(model, present);
        break;
      }
    }
  }
```

This can lead to unpredictable behavior if the state predicates are not mutually exclusive, and this is very easy to do in an app that is more complex than a todo list, even in the Tic-tac-toe.

**Comment by 509dave16** [comment]
@sompylasar That's very true. I had to be really careful to make the state predicates mutually exclusive. And only one automatic action should be triggered per an evaluation of the next action predicates. What would your recommendation be? I could use switch statements, if/else statements, or iterate over an Array that contains the state predicates in the order that they should be evaluated.

**Comment by sompylasar** [comment]
Please reopen, https://github.com/509dave16/tic-tac-toe-engine/commit/b0ac277edb2a3b7bbeff57c047e3d37f5120325c does not close this issue.

**Comment by sompylasar** [comment]
@509dave16 iterating over an array looks the most correct to me, though I don't quite understand the purpose of all these state predicates and next action predicate yet.

**Comment by 509dave16** [comment]
@sompylasar My apologies. I wasn't using Semantica-Release properly when I made the appropriate changes in a previous commit: https://github.com/509dave16/tic-tac-toe-engine/blob/4eb0b1f863ace2821ed544312f4c2bb28558b271/src/sam/nap.js.

**Comment by 509dave16** [comment]
@sompylasar: As to your other question, the main reason for triggering automatic actions using predicates is that this package was designed to play a Tic Tac Toe game locally with someone or across two clients(using Firebase). When someone makes a move etc.. , the appropriate logic(i.e. automatic action) executes based on whether or not the Game Type is "Local Game". The architecture of this package is loosely based off of the SAM pattern: http://sam.js.org/

**Comment by 509dave16** [comment]
@sompylasar If you have any other recommendations regarding documentation, etc.. , let me know. I would be more than happy to take action on your feedback.

**Comment by sompylasar** [comment]
> @sompylasar My apologies. I wasn't using Semantica-Release properly when I made the appropriate changes in a previous commit: https://github.com/509dave16/tic-tac-toe-engine/blob/4eb0b1f863ace2821ed544312f4c2bb28558b271/src/sam/nap.js.

Ah, I see, great!

**Comment by sompylasar** [comment]
> @sompylasar If you have any other recommendations regarding documentation, etc.. , let me know. I would be more than happy to take action on your feedback.

Sorry. I have read all that SAM stuff and it looks to me 1) over-complicated; 2) too many unclear spots, uncertainties, the author admits flaws of many architecture parts right in the docs; 3) code smell and dirtyness, the author is not a software developer, he makes mistakes in trivial parts of the example code snippets, and even in the abstract diagrams he draws.

I'm not convinced SAM in the form it is presented is suitable for complex frontend apps, in which I am specialized.

**Comment by 509dave16** [comment]
@sompylasar I appreciate your perspective on the SAM pattern. I have to admit that I am not expert on complex frontend apps(at least not yet). I'm trying to get there. What resources would you recommend to me that would help me become an expert?

**Comment by sompylasar** [comment]
Pitifully, you'll need practical experience in building the apps, resources could help to get closer to the "aha!" moment but won't make an expert of you.

**Comment by 509dave16** [comment]
@sompylasar Thanks for your honesty and insight!

**Comment by sompylasar** [comment]
Speaking of resources, I think a lot, trying to grasp different models in my mind, and they,mixed with prior education and experience, match with certain models or thoughts expressed by others, and do not match with some of them. I have to read a lot of other people's opinions expressed in the open source discussions. For example, like this: https://github.com/reactjs/redux/issues/1385#issuecomment-223311062 Sometimes, take part, ask questions, suggest my own thoughts.

**Comment by sompylasar** [comment]
Speaking of SAM, some parts of this model look clever and correct, but the whole picture remains blurry and not thought-through, does not trigger the "yes, that's it! I want to try it out!" thing in me. Redux triggered that immediately, as well as React before.
